version: "3.8"

# Reusable vars
x-var:
  - &node-image node:22

services:
  backend:
    container_name: backend
    entrypoint: sh -c "npm i && npm run start"
    env_file:
      - ./backend/.env
    image: *node-image
    ports: ["3001:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/hc"]
      interval: 30s
      timeout: 10s
      retries: 3
    working_dir: "/app"
    volumes: ["./backend:/app", "/app/node_modules"]

  frontend:
    container_name: frontend
    entrypoint: sh -c "npm ci && npm run dev"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001
      PORT: 3000
      NODE_ENV: development
    image: *node-image
    ports: ["3000:3000"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    working_dir: "/app"
    depends_on:
      backend:
        condition: service_healthy

  caddy:
    container_name: caddy
    profiles: ["caddy"]
    build: ./frontend
    environment:
      NODE_ENV: development
      PORT: 3000
      LOG_LEVEL: info
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
      backend:
        condition: service_healthy
