{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $secretName := "nr-mals" }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if not $secretObj }}
  {{- fail (printf "Secret %s not found in namespace %s" $secretName .Release.Namespace) }}
{{- end }}
{{- $secretData := (get $secretObj "data") }}
{{- if not $secretData }}
  {{- fail (printf "Secret %s data not found in namespace %s" $secretName .Release.Namespace) }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  DATABASE_URL: {{ get $secretData "DATABASE_URL" | quote }}
  CDOGS_CLIENT_ID: {{ get $secretData "CDOGS_CLIENT_ID" | quote }}
  CDOGS_OAUTH_URL: {{ get $secretData "CDOGS_OAUTH_URL" | quote }}
  CDOGS_SECRET: {{ get $secretData "CDOGS_SECRET" | quote }}
  CDOGS_URL: {{ get $secretData "CDOGS_URL" | quote }}
  KEYCLOAK_PUBLIC_KEY: {{ get $secretData "KEYCLOAK_PUBLIC_KEY" | quote }}
  KEYCLOAK_SECRET: {{ get $secretData "KEYCLOAK_SECRET" | quote }}
{{- end }}
