
SET search_path TO mals_app;


/*
  Query to generate statements

	select 'alter table mals_app.' || table_name || ' alter column id set generated by default;'
	from information_schema.tables 
	where table_schema = 'mals_app' 
	and table_type = 'BASE TABLE' 
	order by table_name;

	select distinct 'alter table mals_app.' || event_object_table || ' disable trigger ' || trigger_name || ';'
	from information_schema.triggers 
	where trigger_schema = 'mals_app' ;
*/

--  Alter table statements for Talend tDBRow prior to any data loads.

--"
alter table mals_app.mal_add_reason_code_lu alter column id set generated by default;
alter table mals_app.mal_apiary_inspection alter column id set generated by default;
alter table mals_app.mal_application_role alter column id set generated by default;
alter table mals_app.mal_application_user alter column id set generated by default;
alter table mals_app.mal_city_lu alter column id set generated by default;
alter table mals_app.mal_dairy_farm_species_code_lu alter column id set generated by default;
alter table mals_app.mal_dairy_farm_species_sub_code_lu alter column id set generated by default;
alter table mals_app.mal_dairy_farm_tank alter column id set generated by default;
alter table mals_app.mal_dairy_farm_test_infraction_lu alter column id set generated by default;
alter table mals_app.mal_dairy_farm_test_job alter column id set generated by default;
alter table mals_app.mal_dairy_farm_test_result alter column id set generated by default;
alter table mals_app.mal_dairy_farm_test_threshold_lu alter column id set generated by default;
alter table mals_app.mal_delete_reason_code_lu alter column id set generated by default;
alter table mals_app.mal_fur_farm_inventory alter column id set generated by default;
alter table mals_app.mal_game_farm_inventory alter column id set generated by default;
alter table mals_app.mal_licence alter column id set generated by default;
alter table mals_app.mal_licence alter column licence_number set generated by default;
alter table mals_app.mal_licence_comment alter column id set generated by default;
alter table mals_app.mal_licence_parent_child_xref alter column id set generated by default;
alter table mals_app.mal_licence_registrant_xref alter column id set generated by default;
alter table mals_app.mal_licence_species_code_lu alter column id set generated by default;
alter table mals_app.mal_licence_species_sub_code_lu alter column id set generated by default;
alter table mals_app.mal_licence_type_lu alter column id set generated by default;
alter table mals_app.mal_licence_type_parent_child_xref alter column id set generated by default;
alter table mals_app.mal_plant_code_lu alter column id set generated by default;
alter table mals_app.mal_premises_detail alter column id set generated by default;
alter table mals_app.mal_premises_job alter column id set generated by default;
alter table mals_app.mal_print_job alter column id set generated by default;
alter table mals_app.mal_print_job alter column print_job_number set generated by default;
alter table mals_app.mal_print_job_output alter column id set generated by default;
alter table mals_app.mal_region_lu alter column id set generated by default;
alter table mals_app.mal_regional_district_lu alter column id set generated by default;
alter table mals_app.mal_registrant alter column id set generated by default;
alter table mals_app.mal_sale_yard_inventory alter column id set generated by default;
alter table mals_app.mal_sale_yard_species_code_lu alter column id set generated by default;
alter table mals_app.mal_sale_yard_species_sub_code_lu alter column id set generated by default;
alter table mals_app.mal_site alter column id set generated by default;
alter table mals_app.mal_status_code_lu alter column id set generated by default;

alter table mals_app.mal_add_reason_code_lu disable trigger mal_trg_add_reason_code_lu_biu;
alter table mals_app.mal_apiary_inspection disable trigger mal_trg_apiary_inspection_biu;
alter table mals_app.mal_application_role disable trigger mal_trg_application_role_biu;
alter table mals_app.mal_application_user disable trigger mal_trg_application_user_biu;
alter table mals_app.mal_city_lu disable trigger mal_trg_city_lu_biu;
alter table mals_app.mal_dairy_farm_species_code_lu disable trigger mal_trg_dairy_farm_species_code_lu_biu;
alter table mals_app.mal_dairy_farm_species_sub_code_lu disable trigger mal_trg_dairy_farm_species_sub_code_lu_biu;
alter table mals_app.mal_dairy_farm_tank disable trigger mal_trg_dairy_farm_tank_biu;
alter table mals_app.mal_dairy_farm_test_infraction_lu disable trigger mal_trg_dairy_farm_test_infraction_lu_biu;
alter table mals_app.mal_dairy_farm_test_job disable trigger mal_trg_dairy_farm_test_job_biu;
alter table mals_app.mal_dairy_farm_test_result disable trigger mal_trg_dairy_farm_test_result_biu;
alter table mals_app.mal_dairy_farm_test_threshold_lu disable trigger mal_trg_dairy_farm_test_threshold_lu_biu;
alter table mals_app.mal_delete_reason_code_lu disable trigger mal_trg_delete_reason_code_lu_biu;
alter table mals_app.mal_fur_farm_inventory disable trigger mal_trg_fur_farm_inventory_biu;
alter table mals_app.mal_game_farm_inventory disable trigger mal_trg_game_farm_inventory_biu;
alter table mals_app.mal_licence disable trigger mal_trg_licence_biu;
alter table mals_app.mal_licence_comment disable trigger mal_trg_licence_comment_biu;
alter table mals_app.mal_licence_parent_child_xref disable trigger mal_trg_licence_parent_child_xref_biu;
alter table mals_app.mal_licence_registrant_xref disable trigger mal_trg_licence_registrant_xref_biu;
alter table mals_app.mal_licence_species_code_lu disable trigger mal_trg_licence_species_code_lu_biu;
alter table mals_app.mal_licence_species_sub_code_lu disable trigger mal_trg_licence_species_sub_code_lu_biu;
alter table mals_app.mal_licence_type_lu disable trigger mal_trg_licence_type_lu_biu;
alter table mals_app.mal_licence_type_parent_child_xref disable trigger mal_trg_licence_type_parent_child_xref_biu;
alter table mals_app.mal_plant_code_lu disable trigger mal_trg_plant_code_lu_biu;
alter table mals_app.mal_premises_detail disable trigger mal_trg_premises_detail_biu;
alter table mals_app.mal_premises_job disable trigger mal_trg_premises_job_biu;
alter table mals_app.mal_print_job disable trigger mal_trg_print_job_biu;
alter table mals_app.mal_print_job_output disable trigger mal_trg_print_job_output_biu;
alter table mals_app.mal_region_lu disable trigger mal_trg_region_lu_biu;
alter table mals_app.mal_regional_district_lu disable trigger mal_trg_regional_district_lu_biu;
alter table mals_app.mal_registrant disable trigger mal_trg_registrant_biu;
alter table mals_app.mal_sale_yard_inventory disable trigger mal_trg_sale_yard_inventory_biu;
alter table mals_app.mal_sale_yard_species_code_lu disable trigger mal_trg_sale_yard_species_code_lu_biu;
alter table mals_app.mal_sale_yard_species_sub_code_lu disable trigger mal_trg_sale_yard_species_sub_code_lu_biu;
alter table mals_app.mal_site disable trigger mal_trg_site_biu;
alter table mals_app.mal_status_code_lu disable trigger mal_trg_status_code_lu_biu;
--"
